### ISSUE TITLE
Unable to change value of memory adresses

### ISSUE THREAD

**Issue by ktlknss** [mkrueger/game_cheetah#21]
Whenever I click on a value text box, it auto focuses on the narrow results top box so I cannot change any values
I am on the latest git version building from source and all I did was
```sh
cargo build --release
```
and whatever it told me to do as well

I am using Pop!_OS with AwesomeWM and Picom

![scre](https://github.com/mkrueger/game_cheetah/assets/123871807/99cbebca-b7b2-4e02-9edb-49234aefa5ba)

> Note: You may need the nightly toolchain of rust

I haven't done this, which may be the issue but doesn't make much sense

**Comment by mkrueger** [comment]
Saw  it today - didn't get an email notification. What this proofs is that I don't cheat enough! 
(Or play games where it's possible :))
